### ISSUE TITLE
start firefox error message

### ISSUE THREAD

**Issue by cnfczn** [5digits/dactyl#133] opened 2016-01-19 14:16 UTC
This is with Firefox 43 onLinux and Pentadactyl  b9849df .
Error message is printed first time you start Firefox.

:messages
e://dactyl/base.jsm:2029: Ary#iterValues is deprecated: Please use Array#values instead.
resource://dactyl/base.jsm:2014: toArray is deprecated: Please use Array.from instead.
resource://dactyl-content/modes.js:312: Ary#iterValues is deprecated: Please use Array#values instead.
resource://dactyl/template.jsm:178: Ary#iterValues is deprecated: Please use Array#values instead.
resource://dactyl-content/mappings.js:318: Ary#iterValues is deprecated: Please use Array#values instead.
resource://dactyl/buffer.jsm:1083: Ary#iterValues is deprecated: Please use Array#values instead.

**Comment by veeven** [comment] 2016-01-20 06:45
This is probably a duplicate of #120.

**Comment by polyzen** [comment] 2016-03-05 18:51
The last line of @cnfczn's doesn't appear in #120

**Comment by lehasb** [comment] 2016-03-11 11:07
This also occurs on Firefox 43 running on Windows 7/10. The last line (buffer.jsm:1083) doesn't occur at startup, but occasionally pops up later (probably just something different for startup options in _pentadactylrc).

**Closed** 2019-01-18 00:12 UTC
