### ISSUE TITLE
NoScript plugin doesn't work on Firefox 42

### ISSUE THREAD

**Issue by satan1st** [5digits/dactyl#105] opened 2015-11-21 11:30 UTC
The NoScript plugin produce following Error on FF 42:
```
Sourcing file: /home/philipp/.pentadactyl/plugins/noscript-dev.js:291: TypeError: calling a builtin Set constructor without new is forbidden
```

**Comment by willsALMANJ** [comment] 2015-11-21 13:51
Pretty much all of the plugins hosted on 5digits.org have been broken since Firefox 36 (see #23). I would guess that is the issue here (related to breaking changes that Firefox made back then to how array iterators worked), unless the plugin was working for you in Firefox 41?

**Comment by satan1st** [comment] 2015-11-21 15:12
[2015-11-21 05:51] willsALMANJ <notifications@github.com>
> unless the plugin was working for you in
>  Firefox 41?

It was working with Firefox 41.

**Comment by wichtounet** [comment] 2015-11-22 11:09
I personnally have no issue on FF 42 with Noscript and Pentadactyl

**Comment by willsALMANJ** [comment] 2015-11-22 11:42
Note: we are talking about the NoScript Pentadactyl plugin from 5digits.org, not the NoScript Firefox add-on (the Pentadactyl plugin provides bindings for the  NoScript Firefox add-on).

**Comment by troyp** [comment] 2015-11-22 20:28
> Pretty much all of the plugins hosted on 5digits.org have been broken since Firefox 36

Actually, a number of the plugins seem to have been updated in the last year or so. (Although some of them — those with minor changes like E4X removal — haven't raised their version number.)

**Comment by willsALMANJ** [comment] 2015-11-23 03:51
Hmm, it seems like the hg repo for 5digits.org is not available any more to check the changelog of the plugins. js-completion at least is still broken. I thought I used a couple others that were broken, but it seems like they are all third party plugins.

Regarding the NoScript plugin, going by the Developer Notes for Firefox 42, I would guess that the problem is related to the change that `Set()` without `new` now gives a `TypeError`. The plugin uses some custom constructs from Pentadactyl (namely calls like `get set() RealSet(...)` where `RealSet` is the normal `Set()` class) that I am having trouble deciphering the purpose of.

**Comment by willsALMANJ** [comment] 2015-11-23 06:25
I still don't fully understand the `get set() RealSet(...)` syntax, but just adding `new` in front of each instance of `RealSet` seems to fix the plugin. You can use https://gist.github.com/willsALMANJ/accc083077f6996de7f8 if you don't want to do that yourself.

**Comment by satan1st** [comment] 2015-11-23 10:57
Thanks, this works.

Can you bring this upstream, or shall I write a mail to the Author?

**Comment by xrchz** [comment] 2015-11-24 03:28
:+1:

**Comment by willsALMANJ** [comment] 2015-11-24 04:37
Well, this plugin file is not in this dactyl repo, but its author is @kmaglione (one of the owners of this repo) and I don't think the plugin is associated with any other public bug tracker, so maybe it's best to just leave this issue open for now and hope he updates the file on 5digits.org.

**Comment by willsALMANJ** [comment] 2015-12-21 04:11
The 5digits.org plugins have now been added to this repo. https://github.com/5digits/dactyl/commit/174f4ec6362e56b8693db92e022fac5848b80443 should fix this issue.

**Comment by polyzen** [comment] 2016-05-01 12:49
@satan1st, is this resolved for you?

**Comment by satan1st** [comment] 2016-05-01 14:02
[2016-05-01 05:49] "Daniel M. Capella" <notifications@github.com>
> @satan1st, is this resolved for you?

Yes

**Comment by polyzen** [comment] 2016-05-01 16:32
@satan1st, please close this when you get the chance.

**Closed** 2016-05-01 21:23 UTC
